# NUMPY PRACTICE

In [66]:
import numpy as np

In [67]:
d1 = np.arange(1 ,10)

In [68]:
empty = np.empty(9)
empty

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 6.12641401e-321, 7.56599806e-307, 1.42410974e-306,
       5.97819431e-322])

In [69]:
d = np.zeros((2,3), dtype = ('uint'))
print(d.dtype)

uint32


In [70]:
d2 = d1.reshape(3,3)

In [71]:
d3 = np.arange(1,19).reshape(2,3,3)

In [72]:
d1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
d2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [75]:
d1[:3]

array([1, 2, 3])

In [76]:
d1[-7:-4]

array([3, 4, 5])

In [77]:
d2[1:2,:2]

array([[4, 5]])

In [78]:
d3[1:2,:2]

array([[[10, 11, 12],
        [13, 14, 15]]])

In [79]:
d2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
d2[[2,1]]

array([[7, 8, 9],
       [4, 5, 6]])

In [81]:
d2[[2,1],[1]]

array([8, 5])

In [82]:
d2[[2,1],[2]]

array([9, 6])

In [83]:
pr = np.array([5,7,4,2,1,9,8,0,7,5,2])
pr[pr<5]

array([4, 2, 1, 0, 2])

In [84]:
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [93]:
d3[:1,:,1]

array([[2, 5, 8]])

# PANDAS

In [95]:
import pandas as pd

In [115]:
dictionary = {"Name":["Rafiq","Raheel","Areeb","Osama","Haseeb"],"Age":[21,32,43,54,12],"Marks":[98,89,89,99,98]}
data = pd.DataFrame(dictionary,index = range(1,6))
data

Name  Age  Marks
1   Rafiq   21     98
2  Raheel   32     89
3   Areeb   43     89
4   Osama   54     99
5  Haseeb   12     98

In [127]:
csv = pd.read_csv('TAXRATES1.csv')
csv

State ZipCode      TaxRegionName  StateRate  EstimatedCombinedRate  \
0    AK     one  ANCHORAGE BOROUGH        0.0                    0.0   
1    AK     one  ANCHORAGE BOROUGH        0.0                    NaN   
2    AK     two  ANCHORAGE BOROUGH        0.0                    0.0   
3    AK     two  ANCHORAGE BOROUGH        NaN                    0.0   

   EstimatedCountyRate  EstimatedCityRate  EstimatedSpecialRate  RiskLevel  
0                  0.0                NaN                   0.0          1  
1                  0.0                0.0                   0.0          2  
2                  NaN                0.0                   NaN          3  
3                  0.0                0.0                   0.0          4