In [2]:
#Numpy is compiled library and it consist of wrapper code

In [3]:
import numpy as np

In [4]:

'''1 Dimensional Array '''
arr = [10,2,4,6,9]
idx=0
for num in arr:
    arr[idx] = num*2
    idx +=1
print(arr)

[20, 4, 8, 12, 18]


In [5]:
'''Multiplication with 2 easy steps with numpy'''
arr2 = np.array(arr)
print(arr2*2)

[40  8 16 24 36]


In [6]:
data = np.random.rand(5,2,4)
print(data)
print(data.shape)
print(data.dtype)
print(data.ndim)      #Tells the dimension of array

[[[0.76885712 0.60908443 0.65393738 0.18166847]
  [0.29942169 0.63966668 0.29261826 0.4839944 ]]

 [[0.03815566 0.0359761  0.63722681 0.72791774]
  [0.58016727 0.50787966 0.08534072 0.42708299]]

 [[0.37057411 0.76377922 0.82809995 0.21659345]
  [0.01048624 0.10721268 0.6506691  0.36703279]]

 [[0.23045707 0.27029393 0.30348392 0.87143374]
  [0.04725088 0.67082951 0.63558708 0.12441512]]

 [[0.36844372 0.25369912 0.33464062 0.67034928]
  [0.83907843 0.26452229 0.95946803 0.28347477]]]
(5, 2, 4)
float64
3


In [7]:
arr3 = np.array([12,2,3,4,9.0]).astype('uint32')
print(arr3.dtype)
print(arr3>5)

uint32
[ True False False False  True]


In [8]:
arr = np.zeros(2)
print(arr)
arr = np.empty(3)
print(arr)

[0. 0.]
[1.34983320e-311 0.00000000e+000 1.39610347e-309]


# 2 Dimensional Array

In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]]).astype('uint32')
print(arr2.ndim)
print(arr2.shape)
print(arr2>5)
ages = arr2>5
print(ages)
print(np.sum(ages))          #It will tell the number of trues.

2
(2, 3)
[[False False False]
 [False False  True]]
[[False False False]
 [False False  True]]
1


In [10]:
'''arange will return 10 range array'''
arr = np.arange(2,10)
arr2 = np.arange(-1,9)
print(arr2)
print(arr)
arr[-2:] = 33
print(arr)

[-1  0  1  2  3  4  5  6  7  8]
[2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7 33 33]


In [12]:
arr = np.array([1,2,3,4])
arr_slice = arr[1:4]
print(arr_slice)
arr_slice = arr_slice * 0.5
print(arr_slice)
print(arr)

[2 3 4]
[1.  1.5 2. ]
[1 2 3 4]


In [30]:
arr2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2d[1])
print(arr2d[1][0])
print(arr2d [1,0])

[5 6 7 8]
5
5


In [15]:
arr2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2d[0: 3, 1: ])

[[2 3 4]
 [6 7 8]]


In [16]:
ages = np.array([20,13,12,22,11,15,19])
print(ages >15)

[ True False False  True False False  True]


In [17]:
'''Fancy Indexing'''
print(arr2d)
print('---------')
print(arr2d[[1]])
print('---------')
print(arr2d)

[[1 2 3 4]
 [5 6 7 8]]
---------
[[5 6 7 8]]
---------
[[1 2 3 4]
 [5 6 7 8]]


In [18]:
'''Transpose'''
print(arr2d)
print()
print(arr2d.T)
print()
print(arr2d)

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 2 3 4]
 [5 6 7 8]]
